// Generated by https://quicktype.io
export interface ITopoJson {
    type: string;
    arcs: Array<Array<number[]>>;
    transform: ITransform;
    objects: IObjects;
}

export interface IObjects {
    circonscriptions: ICirconscriptions;
}

export interface ICirconscriptions {
    type: string;
    geometries: IGeometry[];
}

export interface IGeometry {
    arcs: Array<Array<number[] | number>>;
    type: keyof typeof Type;
    properties: { [key: string]: any }
}


export const Type = {
    MultiPolygon: "MultiPolygon",
    Polygon: "Polygon",
} as const

export interface ITransform {
    scale: number[];
    translate: number[];
}