// Generated by https://quicktype.io
declare interface ITopoJson {
    type: string;
    arcs: Array<Array<number[]>>;
    transform: Transform;
    objects: Objects;
}

declare  interface Objects {
    circonscriptions: Circonscriptions;
}

declare  interface Circonscriptions {
    type: string;
    geometries: Geometry[];
}

declare  interface Geometry {
    arcs: Array<Array<number[] | number>>;
    type: keyof typeof Type;
    properties: { [key: string]: any }
}


declare  const Type =  {
    MultiPolygon: "MultiPolygon",
    Polygon: "Polygon",
} as const

declare  interface Transform {
    scale: number[];
    translate: number[];
}