export interface ICandidatesBC {
    EVENT_NAME:       EventName;
    ED_ABBREVIATION:  EdAbbreviation;
    ED_NAME:          EdName;
    CANDIDATE:        string;
    ELECTED:          Elected;
    AFFILIATION:      Affiliation;
    VOTES_CONSIDERED: number;
    VOTE_CATEGORY:    VoteCategory;
}

export const Affiliation = {
    BCGreenParty = "BC Green Party",
    BCLiberalParty = "BC Liberal Party",
    BCVision = "B.C. Vision",
    BcNdp = "BC NDP",
    ChristianHeritagePartyOfBC = "Christian Heritage Party of B.C.",
    CommunistPartyOfBC = "Communist Party of BC",
    Conservative = "Conservative",
    Independent = "Independent",
    Libertarian = "Libertarian",
    RuralBCParty = "Rural BC Party",
    WexitBC = "Wexit BC",
} as const

export const EdAbbreviation = {
    ABM = "ABM",
    Abs = "ABS",
    Abw = "ABW",
    Bds = "BDS",
    Bnd = "BND",
    Bne = "BNE",
    Bnl = "BNL",
    Bnn = "BNN",
    CLR = "CLR",
    CRC = "CRC",
    Cbc = "CBC",
    Cbn = "CBN",
    Chc = "CHC",
    Chk = "CHK",
    Cqb = "CQB",
    Cqm = "CQM",
    Cwv = "CWV",
    Dln = "DLN",
    Dls = "DLS",
    Esm = "ESM",
    Frn = "FRN",
    Kan = "KAN",
    Kas = "KAS",
    Kla = "KLA",
    Klm = "KLM",
    Klw = "KLW",
    Koe = "KOE",
    Kow = "KOW",
    Ljf = "LJF",
    Lly = "LLY",
    Lye = "LYE",
    Mam = "MAM",
    Map = "MAP",
    Mpr = "MPR",
    NOC = "NOC",
    Nan = "NAN",
    Ncw = "NCW",
    Nec = "NEC",
    Nel = "NEL",
    New = "NEW",
    Noi = "NOI",
    Nvl = "NVL",
    Nvs = "NVS",
    Obg = "OBG",
    Paq = "PAQ",
    Pcn = "PCN",
    Pcs = "PCS",
    Pen = "PEN",
    Poc = "POC",
    Pom = "POM",
    Por = "POR",
    Prm = "PRM",
    Prv = "PRV",
    Rnc = "RNC",
    Rqe = "RQE",
    Rsc = "RSC",
    Rst = "RST",
    SAN = "SAN",
    SAS = "SAS",
    SUS = "SUS",
    Shu = "SHU",
    Ske = "SKE",
    Skn = "SKN",
    Src = "SRC",
    Srf = "SRF",
    Srg = "SRG",
    Sug = "SUG",
    Sun = "SUN",
    Sup = "SUP",
    Swh = "SWH",
    Swr = "SWR",
    Vfa = "VFA",
    Vfc = "VFC",
    Vfv = "VFV",
    Vha = "VHA",
    Vke = "VKE",
    Vki = "VKI",
    Vla = "VLA",
    Vmp = "VMP",
    Vnp = "VNP",
    Vnq = "VNQ",
    Vnw = "VNW",
    Vrm = "VRM",
    Vtb = "VTB",
    Vts = "VTS",
    Wvc = "WVC",
    Wvs = "WVS",
} as const

export const EdName = {
    AbbotsfordMission = "Abbotsford-Mission",
    AbbotsfordSouth = "Abbotsford South",
    AbbotsfordWest = "Abbotsford West",
    BoundarySimilkameen = "Boundary-Similkameen",
    BurnabyDeerLake = "Burnaby-Deer Lake",
    BurnabyEdmonds = "Burnaby-Edmonds",
    BurnabyLougheed = "Burnaby-Lougheed",
    BurnabyNorth = "Burnaby North",
    CaribooChilcotin = "Cariboo-Chilcotin",
    CaribooNorth = "Cariboo North",
    Chilliwack = "Chilliwack",
    ChilliwackKent = "Chilliwack-Kent",
    ColumbiaRiverRevelstoke = "Columbia River-Revelstoke",
    CoquitlamBurkeMountain = "Coquitlam-Burke Mountain",
    CoquitlamMaillardville = "Coquitlam-Maillardville",
    CourtenayComox = "Courtenay-Comox",
    CowichanValley = "Cowichan Valley",
    DeltaNorth = "Delta North",
    DeltaSouth = "Delta South",
    EsquimaltMetchosin = "Esquimalt-Metchosin",
    FraserNicola = "Fraser-Nicola",
    KamloopsNorthThompson = "Kamloops-North Thompson",
    KamloopsSouthThompson = "Kamloops-South Thompson",
    KelownaLakeCountry = "Kelowna-Lake Country",
    KelownaMission = "Kelowna-Mission",
    KelownaWest = "Kelowna West",
    KootenayEast = "Kootenay East",
    KootenayWest = "Kootenay West",
    LangfordJuanDeFuca = "Langford-Juan de Fuca",
    Langley = "Langley",
    LangleyEast = "Langley East",
    MapleRidgeMission = "Maple Ridge-Mission",
    MapleRidgePittMeadows = "Maple Ridge-Pitt Meadows",
    MidIslandPacificRim = "Mid Island-Pacific Rim",
    Nanaimo = "Nanaimo",
    NanaimoNorthCowichan = "Nanaimo-North Cowichan",
    NechakoLakes = "Nechako Lakes",
    NelsonCreston = "Nelson-Creston",
    NewWestminster = "New Westminster",
    NorthCoast = "North Coast",
    NorthIsland = "North Island",
    NorthVancouverLonsdale = "North Vancouver-Lonsdale",
    NorthVancouverSeymour = "North Vancouver-Seymour",
    OakBayGordonHead = "Oak Bay-Gordon Head",
    ParksvilleQualicum = "Parksville-Qualicum",
    PeaceRiverNorth = "Peace River North",
    PeaceRiverSouth = "Peace River South",
    Penticton = "Penticton",
    PortCoquitlam = "Port Coquitlam",
    PortMoodyCoquitlam = "Port Moody-Coquitlam",
    PowellRiverSunshineCoast = "Powell River-Sunshine Coast",
    PrinceGeorgeMackenzie = "Prince George-Mackenzie",
    PrinceGeorgeValemount = "Prince George-Valemount",
    RichmondNorthCentre = "Richmond North Centre",
    RichmondQueensborough = "Richmond-Queensborough",
    RichmondSouthCentre = "Richmond South Centre",
    RichmondSteveston = "Richmond-Steveston",
    SaanichNorthAndTheIslands = "Saanich North and the Islands",
    SaanichSouth = "Saanich South",
    Shuswap = "Shuswap",
    Skeena = "Skeena",
    Stikine = "Stikine",
    SurreyCloverdale = "Surrey-Cloverdale",
    SurreyFleetwood = "Surrey-Fleetwood",
    SurreyGreenTimbers = "Surrey-Green Timbers",
    SurreyGuildford = "Surrey-Guildford",
    SurreyNewton = "Surrey-Newton",
    SurreyPanorama = "Surrey-Panorama",
    SurreySouth = "Surrey South",
    SurreyWhalley = "Surrey-Whalley",
    SurreyWhiteRock = "Surrey-White Rock",
    VancouverFairview = "Vancouver-Fairview",
    VancouverFalseCreek = "Vancouver-False Creek",
    VancouverFraserview = "Vancouver-Fraserview",
    VancouverHastings = "Vancouver-Hastings",
    VancouverKensington = "Vancouver-Kensington",
    VancouverKingsway = "Vancouver-Kingsway",
    VancouverLangara = "Vancouver-Langara",
    VancouverMountPleasant = "Vancouver-Mount Pleasant",
    VancouverPointGrey = "Vancouver-Point Grey",
    VancouverQuilchena = "Vancouver-Quilchena",
    VancouverWestEnd = "Vancouver-West End",
    VernonMonashee = "Vernon-Monashee",
    VictoriaBeaconHill = "Victoria-Beacon Hill",
    VictoriaSwanLake = "Victoria-Swan Lake",
    WestVancouverCapilano = "West Vancouver-Capilano",
    WestVancouverSeaToSky = "West Vancouver-Sea to Sky",
}

export const Elected = {
    N = "N",
    Y = "Y",
} as const

export const EventName = {
    The2020GeneralElection = "2020 General Election",
} as const

export const VoteCategory = {
    Valid = "Valid",
} as const
