// Generated by https://quicktype.io
export interface ITopoJson {
    type: string;
    arcs: Array<Array<number[]>>;
    transform: Transform;
    objects: Objects;
}

export interface Objects {
    circonscriptions: Circonscriptions;
}

export interface Circonscriptions {
    type: string;
    geometries: Geometry[];
}

export interface Geometry {
    arcs: Array<Array<number[] | number>>;
    type: Type;
    properties: { [key: string]: any }
}

// export interface Properties {
//     CO_CEP:    number;
//     NM_CEP:    string;
//     NMTRI_CEP: string;
// }

export enum Type {
    MultiPolygon = "MultiPolygon",
    Polygon = "Polygon",
}

export interface Transform {
    scale: number[];
    translate: number[];
}